### ISSUE TITLE
Breaks some link text in navigation

### ISSUE THREAD

**Issue by WillGibson** [mihaigalos/mkdocs-breadcrumbs#2]
Enabling the plugin seems to affect the link text in the side navigation somehow.

Without the plugin...

<img width="232" alt="image" src="https://github.com/user-attachments/assets/759df8d4-2f3a-435a-bd7f-1665077fa8e0">

With the all defaults configuration and 0.1.10 of the plugin...

<img width="225" alt="image" src="https://github.com/user-attachments/assets/3f9f072a-fd16-446f-9564-8916ad3b9178">

Only seems to affect where the files linked to are called `index.md`.

**Comment by mihaigalos** [comment]
Hum. Index is a page generated to list all subpages in its content.
It's recursively generated for all subfolders.

What's you nav entry in the `mkdocs.yaml` looking like? - can you provide a minimal example?

**Comment by WillGibson** [comment]
There is no `nav` entry as such.

```yaml
# mkdocs.yml
...
theme:
  name: material
  ...
  features:
    ...
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
...
plugins:
  - literate-nav:
      nav_file: navigation.md
...
```

```markdown
# docs/navigation.md
...
    * [Configure databases & other extensions](reference/configure-databases-and-other-extensions/index.md)
        * [Application load Balancer](reference/configure-databases-and-other-extensions/application-load-balancer.md)
        * [Domain Names and DNS](reference/configure-databases-and-other-extensions/domains-and-dns.md)
        * [Monitoring](reference/configure-databases-and-other-extensions/monitoring.md)
        * [OpenSearch](reference/configure-databases-and-other-extensions/opensearch.md)
        * [PostgreSQL](reference/configure-databases-and-other-extensions/postgresql/index.md)
            * [Backup and restore from a snapshot](reference/configure-databases-and-other-extensions/postgresql/backup-and-restore-from-a-snapshot.md)
            * [Backup and restore from a point in time](reference/configure-databases-and-other-extensions/postgresql/backup-and-restore-from-a-point-in-time.md)
        * [Redis](reference/configure-databases-and-other-extensions/redis.md)
        * [S3](reference/configure-databases-and-other-extensions/s3.md)
        * [Plans](reference/configure-databases-and-other-extensions/plans.md)
...
```
